import {createConstants} from '../utils';

export default {
    LOGIN_USER_REQUEST:'LOGIN_USER_REQUEST',
    LOGIN_USER_FAILURE:'LOGIN_USER_FAILURE',
    LOGIN_USER_SUCCESS: 'LOGIN_USER_SUCCESS',
    LOGOUT_USER:'LOGOUT_USER',
    FETCH_PROTECTED_DATA_REQUEST:'FETCH_PROTECTED_DATA_REQUEST',
    RECEIVE_PROTECTED_DATA:'RECEIVE_PROTECTED_DATA',
    SAVE_BROADCAST : 'SAVE_BROADCAST',
    CURRENT_ENVIRONMENT : 'CURRENT_ENVIRONMENT',
    PUBLIC_TOKEN : 'PUBLIC_TOKEN',
    FETCH_ACTIVE_STREAMS : 'FETCH_ACTIVE_STREAMS',
    LOGIN_ARTIST_SUCCESS : 'LOGIN_ARTIST_SUCCESS',
    VIEW_COUNT_UPDATE : 'VIEW_COUNT_UPDATE',
    ARTIST_STREAMING_STATUS : 'ARTIST_STREAMING_STATUS',
    UPLOAD_IMAGE : 'UPLOAD_IMAGE',
    FETCH_REGISTERED_ARTISTS : 'FETCH_REGISTERED_ARTISTS',
    FILTER_REGISTERED_ARTISTS : 'FILTER_REGISTERED_ARTISTS',
    FETCH_ALL_STREAMS : 'FETCH_ALL_STREAMS',
    PERFORMANCE_DETAIL_UPDATE : 'PERFORMANCE_DETAIL_UPDATE',
    PERFORMANCE_DETAIL_SUCCESS : 'PERFORMANCE_DETAIL_SUCCESS',
    PERFORMANCE_DETAIL_FAILURE : 'PERFORMANCE_DETAIL_FAILURE',
    SUBSCRIPTION_STATUS : 'SUBSCRIPTION_STATUS',
    ADD_TAG: 'ADD_TAG'
};
