import {createConstants} from '../utils';

export default {
    LOGIN_USER_REQUEST:'LOGIN_USER_REQUEST',
    LOGIN_USER_FAILURE:'LOGIN_USER_FAILURE',
    LOGIN_USER_SUCCESS: 'LOGIN_USER_SUCCESS',
    LOGOUT_USER:'LOGOUT_USER',
    FETCH_PROTECTED_DATA_REQUEST:'FETCH_PROTECTED_DATA_REQUEST',
    RECEIVE_PROTECTED_DATA:'RECEIVE_PROTECTED_DATA',
    SAVE_BROADCAST : 'SAVE_BROADCAST',
    CURRENT_ENVIRONMENT : 'CURRENT_ENVIRONMENT',
    PUBLIC_TOKEN : 'PUBLIC_TOKEN'
};
